service/routes.py, tests/test_routes.py
I added codes for listing orders, can yall take a look? Thanks
=> Add Listing Function

service/routes.py, tests/test_routes.py
Use /orders/<order_id> to view an order
=> View an order

service/routes.py, tests/test_routes.py
I added update function, please take a look, thanks!
=> update an order

service/routes.py, tests/test_routes.py
Add API endpoint to delete an item from an order and required tests
=> Add API endpoint to delete an item from an order

service/routes.py, tests/test_routes.py
=> fix index, add health endpoint

service/routes.py, tests/test_routes.py
Added delete function, please take a look, thanks!
=> Add endpoint to delete an order

service/models.py, service/routes.py, tests/test_order.py, tests/test_routes.py
=> Add test cases to improve coverage

service/routes.py, tests/test_routes.py
I fixed 415/404 and added List Order Items, please take a look
=> Fix 415/404 and Add List Order Items

service/routes.py, tests/test_routes.py
Fixed: POST /orders with a bad data caused a 500_INTERNAL_SERVER_ERROR instead of 400_BAD_REQUEST
=> Fix orders bug

service/models.py, service/routes.py, tests/factories.py, tests/test_item.py, tests/test_order.py, tests/test_routes.py
Increase code linting score to 10/10
=> Increase code linting score to 10/10

tests/test_routes.py
Remove extra line about test case
=> Remove extra line about test case

service/routes.py, tests/test_routes.py
Added codes for the action to change the order status.
=> Add Codes to Change Status

.github/workflows/workflow.yml, README.md
=> Add codecov to repository

service/routes.py
Update index URL to return JSON. Update root URL info
=> Update index URL to return JSON instead of text/html

service/__init__.py, service/common/error_handlers.py, service/models.py, service/routes.py, tests/test_order.py, tests/test_routes.py
Made the following changes :
-Added test case to account
-Made Corrections in error handlings
-Added new attributes
=> Add complete order route

service/__init__.py, service/common/error_handlers.py, service/models.py, service/routes.py, tests/test_order.py, tests/test_routes.py
Reverts CSCI-GA-2820-SU24-001/orders#57
=> Revert "Add complete order route"

.github/workflows/workflow.yml, service/routes.py, tests/test_routes.py
Added codes for item filtering functions, plz have a look
=> Added item filters

.tekton/events/event_listener.yaml, .tekton/events/trigger.yaml, .tekton/events/trigger_binding.yaml, .tekton/events/trigger_template.yaml, .tekton/pipeline.yaml, .tekton/tasks.yaml, .tekton/workspace.yaml
=> Added .tekton folder

features/orders.feature, features/steps/order_steps.py
I added some code for features
=> added code for features

poetry.lock, pyproject.toml, service/__init__.py
I added code from lab-flask-restplus-swagger to __init__.py
=> Add Code to __init__.py

features/orders.feature, features/steps/order_steps.py
=> Add background for BDD

features/orders.feature, features/steps/order_steps.py, service/models.py, service/routes.py, service/static/index.html, service/static/js/rest_api.js, tests/test_routes.py
UI background fix and View all orders
=> UI background fix and View all orders

features/orders.feature, features/steps/order_steps.py, features/steps/web_steps.py, service/models.py, service/routes.py, service/static/index.html, service/static/js/rest_api.js, tests/test_routes.py
Add UI to view all items. BDD test included
=> Add UI to view all items

service/routes.py
I added swagger models and arguments
=> added swagger models

features/orders.feature, features/steps/web_steps.py, service/routes.py, service/static/index.html, service/static/js/rest_api.js, tests/test_routes.py
=> add status query bdd

features/orders.feature, features/steps/order_steps.py, features/steps/web_steps.py, service/models.py, service/routes.py, service/static/index.html, service/static/js/rest_api.js
Add UI to update order and BDD test
=> Add UI to update order

features/orders.feature, features/steps/web_steps.py, service/static/index.html, service/static/js/rest_api.js
I added query filter for customer id
=> add query customer id

service/static/js/rest_api.js
=> fix incorrect result

features/orders.feature, service/static/index.html, service/static/js/rest_api.js
Add UI to delete order with BDD test
=> Add UI to delete order

features/orders.feature, service/static/index.html, service/static/js/rest_api.js
=> added action bdd

k8s/service.yaml
Create service.yaml for Kubernetes deployment
=> Create service.yaml for Kubernetes deployment

features/orders.feature
Update orders.feature to restore BDD for delete
=> Update orders.feature to restore BDD for delete
